services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: kotlin_kata_network
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"